FROM szymonrychu/ros-lunar-base:latest

USER root
RUN set -xe;\
    apt-get update;\
    apt-get install -y ros-lunar-desktop-full

RUN set -xe;\
    apt-get update;\
    apt-get install -y --no-install-recommends \
        git x11vnc xvfb wget python python-numpy unzip openbox geany menu;\
    cd /home/ros;\
    git clone https://github.com/kanaka/noVNC.git;\
    rm -Rf noVNC/.git;\
    cd noVNC/utils;\
    git clone https://github.com/kanaka/websockify websockify;\
    rm -Rf websockify/.git;\
    chown -R ros. /home/ros

COPY gui/startup.sh /

EXPOSE 6080

USER ros

WORKDIR /home/ros

ENTRYPOINT ["/startup.sh"]