FROM szymonrychu/ros-melodic-base:latest

USER root

ADD cmd.sh /
RUN chmod +x /cmd.sh

ADD entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENV ROSCORE_PORT 5000

USER ros 

CMD ["/cmd.sh"]
ENTRYPOINT ["/entrypoint.sh"]