FROM szymonrychu/ros-gui-freenect:latest AS base

USER ros

from base as g2ofork_compilation

RUN set -xe;\
    sudo apt-get purge -y ros-${ROS_DISTRO}-libg2o libqglviewer-dev;\
    sudo apt-get install -y \
        libsuitesparse-dev \
        libeigen3-dev;\
    mkdir -p /home/ros/g2ofork;\
    cd /home/ros/g2ofork;\
    git clone https://github.com/felixendres/g2o.git .;\
    mkdir /home/ros/g2ofork/build /home/ros/g2ofork/install;\
    cd /home/ros/g2ofork/build /home/ros/g2ofork/install;\
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/ros/g2ofork/install -DG2O_BUILD_EXAMPLES=OFF;\
    make -j2 install

FROM base AS rgbdslam_v2_compilation

COPY --from=g2ofork_compilation /home/ros/g2ofork/install /home/ros/g2ofork/install

RUN bash -ec "\
        rosdep update;\
        sudo apt-get install -y \
            libglew-dev \
            liballegro4.4 \
            libcaca0 \
            libdevil1c2 \
            liblcms2-dev \
            libsdl1.2debian \
            libdevil-dev \
            libsuitesparse-dev \
            libslang2;\
        source /opt/ros/${ROS_DISTRO}/setup.bash;\
        export G2O_DIR=/home/ros/g2ofork/install;\
        mkdir -p /home/ros/rgbdslam_catkin_ws/src;\
        cd /home/ros/rgbdslam_catkin_ws/src;\
        catkin_init_workspace;\
        cd /home/ros/rgbdslam_catkin_ws;\
        catkin_make;\
        source /home/ros/rgbdslam_catkin_ws/devel/setup.bash;\
        git clone -b ${ROS_DISTRO} https://github.com/szymonrychu/rgbdslam_v2.git /home/ros/rgbdslam_catkin_ws/src/rgbdslam;\
        rosdep install rgbdslam;\
        catkin_make -j2;\
    "


USER ros