FROM szymonrychu/ros-melodic-base:latest

USER root

# Build arguments.
ARG VCS_REF
ARG BUILD_DATE
ARG MESA_DEMOS="false"

# Install all needed deps and compile the mesa llvmpipe driver from source.
RUN set -xe; \
    apt-get update && apt-get install -y xvfb llvm wget; \
    mkdir -p /var/tmp/build; \
    cd /var/tmp/build; \
    wget "https://mesa.freedesktop.org/archive/mesa-18.0.1.tar.gz"; \
    tar xfv mesa-18.0.1.tar.gz; \
    rm mesa-18.0.1.tar.gz; \
    cd mesa-18.0.1; \
    ./configure --enable-glx=gallium-xlib --with-gallium-drivers=swrast,swr --disable-dri --disable-gbm --disable-egl --enable-gallium-osmesa --prefix=/usr/local; \
    make; \
    make install; \
    cd .. ; \
    rm -rf mesa-18.0.1;

# Copy our entrypoint into the container.
COPY gui_entrypoint.sh /usr/local/bin/entrypoint.sh

# Setup our environment variables.
ENV XVFB_WHD="1920x1080x24" \
    DISPLAY=":99" \
    LIBGL_ALWAYS_SOFTWARE="1" \
    GALLIUM_DRIVER="llvmpipe" \
    LP_NO_RAST="false" \
    LP_DEBUG="" \
    LP_PERF="" \
    LP_NUM_THREADS=""

# Set the default command.
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]