---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: kube-system
# kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rosmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosmaster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rosmaster
        ros_version: kinetic
    spec:
      containers:
        - name: rosmaster
          image: szymonrychu/ros:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6080
          volumeMounts:
            - mountPath: /dev/bus/usb
              name: dev-bus-usb
            - mountPath: /home/ros/.ros
              name: ros-dir
          securityContext:
            privileged: true
      volumes:
        - name: dev-bus-usb
          hostPath:
            path: /dev/bus/usb
            type: Directory
        - name: ros-dir
          hostPath:
            path: /home/szymonri/ros
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: rosmaster
  labels:
    app: rosmaster
spec:
  selector:
    app: rosmaster
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6080
      nodePort: 30000