apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rosmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosmaster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rosmaster
        ros_version: kinetic
    spec:
      containers:
      - name: rosmaster
        image: szymonrychu/k8s-ros-master:CIRCLE_SHA1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
